name: Check Secrets Availability

on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required secrets
        env:
          TEST: ${{ secrets.TEST }}

          ASSET_BASE_URL: ${{ secrets.ASSET_BASE_URL }}
          MANIFEST_URL: ${{ secrets.MANIFEST_URL }}
          PATCH_NOTES_BASE_URL: ${{ secrets.PATCH_NOTES_BASE_URL }}
          PATCH_NOTES_URL: ${{ secrets.PATCH_NOTES_URL }}
          VITE_PATCH_NOTES_BASE_URL: ${{ secrets.VITE_PATCH_NOTES_BASE_URL }}

          # Add any other secrets you want to check here
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          secrets_to_check=(
            "TEST"
            "ASSET_BASE_URL"
            "MANIFEST_URL"
            "PATCH_NOTES_BASE_URL"
            "PATCH_NOTES_URL"
            "VITE_PATCH_NOTES_BASE_URL"
          )
          missing_secrets=0
          echo "Checking for required secrets..."
          for secret_name in "${secrets_to_check[@]}"; do
            # Indirectly access the environment variable based on the secret_name
            # The value of the env var (which comes from secrets.*) is checked
            secret_value="${!secret_name}"
            if [ -z "$secret_value" ]; then
              echo "Error: Secret $secret_name is not set or is empty."
              missing_secrets=$((missing_secrets + 1))
            else
              echo "  ✔ Secret $secret_name is present."
            fi
          done

          if [ "$missing_secrets" -gt 0 ]; then
            echo "$missing_secrets secret(s) are missing. Failing the check."
            exit 1
          else
            echo "All checked secrets are present."
          fi
